version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase
  pre_build:
    commands:
      - echo Nothing to do in the pre-build phase
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - npm run build  # Ensure this matches your build command
      - echo Build completed on `date`
      - ls -R  # List all files and directories recursively
  post_build:
    commands:
      - echo Nothing to do in the post-build phase

artifacts:
  files:
    - 'dist/**'  # Adjust this to match your build output directory
  discard-paths: true
